import ListNFT from "components/ListNFT";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-5 sm:px-10 md:px-15 lg:px-20">
        <h1 className="text-[30px] font-medium mt-4 mb-6 border-b border-yellow-300">
          List NFT
        </h1>
        <ListNFT />
      </main>
    </>
  );
}
